### ISSUE TITLE
vue3版本无法使用

### ISSUE THREAD

**Issue by ilzmc** [zyqwst/json-schema-editor-vue3#7]
从npm安装的包， 引入组件之后提示“Component is missing template or render function.” 错误，是不是出错了

**Comment by zyqwst** [comment]
Vue版本，代码片段，报错截图贴出来看看

**Comment by ilzmc** [comment]
导入之后是这样的，vue3+ts环境，1.2.0的版本
![image](https://github.com/zyqwst/json-schema-editor-vue3/assets/53931993/411a2e9b-c678-4196-ac4b-8e5a068cb72d)

![image](https://github.com/zyqwst/json-schema-editor-vue3/assets/53931993/88b70bba-b299-42e3-8ee9-6c69203d29ba)

**Comment by ilzmc** [comment]
vue3+ts环境，npm 安装的包，1.2.0版本
![image](https://github.com/zyqwst/json-schema-editor-vue3/assets/53931993/04da5ba5-d83d-4e62-be91-c2c244b00119)
![image](https://github.com/zyqwst/json-schema-editor-vue3/assets/53931993/9771b04c-7d60-4fe9-9db3-8607adce6916)

**Comment by zyqwst** [comment]
> vue3+ts环境，npm 安装的包，1.2.0版本 ![image](https://private-user-images.githubusercontent.com/53931993/277222142-04da5ba5-d83d-4e62-be91-c2c244b00119.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTQ4NTgsIm5iZiI6MTcwODU5NDU1OCwicGF0aCI6Ii81MzkzMTk5My8yNzcyMjIxNDItMDRkYTViYTUtZDgzZC00ZTYyLWJlOTEtYzJjMjQ0YjAwMTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDA5MzU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMzYzNDY2ZjZjNWMxZmZhY2VkZGFjZmQzMjZmMDE4ZWVlMmJmNDMwODY4NGU1ZjQzYTZhN2Q1NmI0OGU5MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UJr2HXaKX6Lrc36NKGxFrJpXQHRrIoXagqR1wM7mqec) ![image](https://private-user-images.githubusercontent.com/53931993/277222296-9771b04c-7d60-4fe9-9db3-8607adce6916.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTQ4NTgsIm5iZiI6MTcwODU5NDU1OCwicGF0aCI6Ii81MzkzMTk5My8yNzcyMjIyOTYtOTc3MWIwNGMtN2Q2MC00ZmU5LTlkYjMtODYwN2FkY2U2OTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDA5MzU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MDE1ZjI4OTk1MzhiZTAzMTFmYmUxNWM1YWExODdjN2JjYTlhZmJlN2EwNDVhODc4MjAyNmFkMmJlYzJiNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hx9zYAll_DCDYh-ZMvre3oVlUG5Yt_JNq6ye0w6oFQ8)
可以看看这篇文章，尝试处理：https://medium.com/codingbeauty-tutorials/vue-component-is-missing-template-or-render-function-53275060bcff

**Comment by Ning-Jun** [comment]
后来修复了吗
