### ISSUE TITLE
这一行代码是不是有问题？

### ISSUE THREAD

**Issue by Cava425** [zyqwst/json-schema-editor-vue3#9]
https://github.com/zyqwst/json-schema-editor-vue3/blob/80fa20948645ea27d2350b7485f54d3e6d23d6a0/packages/json-schema-editor/main.vue#L317

**Comment by zyqwst** [comment]
麻烦把导致的问题描述下

**Comment by Cava425** [comment]
> 麻烦把导致的问题描述下
map中的箭头函数，`item => +item`是不是多了一个加号，导致某些高级设置不能用
![image](https://github.com/zyqwst/json-schema-editor-vue3/assets/49832946/8509f775-ef33-4a06-af0a-eab7bd225a7c)

**Comment by zyqwst** [comment]
这个不是BUG，你这个节点是数字，只能输入数字
